document.getElementById("demo").style.backgroundColor="skyblue"
document.getElementById("demo").style.height="100px"
document.getElementById("demo1").style.backgroundColor="lightgreen"
document.getElementsByClassName("demo2")[0].style.backgroundColor="blue"
document.getElementsByClassName("demo2")[1].style.backgroundColor="blue"
document.getElementsByClassName("demo3")[0].style.backgroundColor="lightpink"
document.getElementsByName("demo4")[0].style.backgroundColor="beige"
document.getElementsByTagName("li")[0].style.backgroundColor="green"
document.getElementsByTagName("li")[1].style.backgroundColor="crimson"
    